# Generated by Django 2.0.1 on 2018-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latest_cost',
            field=models.IntegerField(default=0),
        ),
    ]
