# Generated by Django 2.0.1 on 2018-01-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0003_auto_20180118_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='unit price')),
                ('object_id', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app.Cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('cart',),
            },
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Commodity',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
