# Generated by Django 2.0.1 on 2018-01-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180123_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('product_image', models.ImageField(blank=True, upload_to='products')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
