# Generated by Django 2.0.1 on 2018-01-31 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20180131_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradinghistory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tradinghistory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tradinghistory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='tradinghistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
