# Generated by Django 2.0.1 on 2018-01-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180201_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradinghistory',
            old_name='subtotal',
            new_name='price',
        ),
    ]
