# Generated by Django 2.0.1 on 2018-01-31 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180201_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinghistory',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
            preserve_default=False,
        ),
    ]
