# Generated by Django 2.0.1 on 2018-01-31 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wheat_futures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheat_futures',
            name='settlement_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
