# Generated by Django 2.0.1 on 2018-01-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180201_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheat_futures',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
